export const PROJECTS_DATA = [
  {
    id: "p1",
    name: "2 & 3 BHK Stilt + 2 Residential Apartment Building with 5 Units",
    location: "Vengaivasel, Chennai",
    bhk: ["2 BHK", "3 BHK"],
    bhkFilter: ["2bhk", "3bhk"],
    units: 5,
    landArea: "2,305 sq.ft",
    builtUpArea: "6,010 sq.ft",
    year: "2024",
    image: "/image/residential_building_10.jpeg",
    aspectRatio: "16/10",
    description: "Modern Stilt + 2 residential apartment building in Vengaivasel featuring 5 spacious 2 & 3 BHK units, stilt parking, RCC frame structure, and premium finishes."
  },
  {
    id: "p2",
    name: "4 BHK G+2 Residential Building",
    location: "Vengaivasel, Chennai",
    bhk: ["4 BHK"],
    bhkFilter: ["4bhk"],
    units: 1,
    landArea: "1,700 sq.ft",
    builtUpArea: "2,300 sq.ft",
    year: "2024",
    image: "/image/residential_building_2.jpeg",
    aspectRatio: "3/4",
    description: "Spacious 4 BHK G+2 independent residential home in Vengaivasel engineered with earthquake-resistant structural design, double-height living room, and private terrace."
  },
  {
    id: "p3",
    name: "2 BHK Stilt + 2 Elite Enclave Residential Apartment with 2 Units",
    location: "Vengaivasel, Chennai",
    bhk: ["2 BHK"],
    bhkFilter: ["2bhk"],
    units: 2,
    landArea: "1,015 sq.ft",
    builtUpArea: "2,100 sq.ft",
    year: "2024",
    image: "/image/residential_building_1.jpeg",
    aspectRatio: "1/1",
    description: "Bespoke 2 BHK Stilt + 2 residential enclave in Vengaivasel offering 2 exclusive apartment units with automated lift, covered parking, and 100% Vaastu planning."
  },
  {
    id: "p4",
    name: "3 BHK G+1 Residential Villa",
    location: "Vengaivasel, Chennai",
    bhk: ["3 BHK"],
    bhkFilter: ["3bhk"],
    units: 1,
    landArea: "800 sq.ft",
    builtUpArea: "1,100 sq.ft",
    year: "2023",
    image: "/image/residential_building_3.jpeg",
    aspectRatio: "16/9",
    description: "Elegantly designed 3 BHK G+1 independent residential villa in Vengaivasel optimizing space utilization, natural illumination, and premium civil construction."
  },
  {
    id: "p5",
    name: "3 BHK G+1 Individual Villa",
    location: "Kaspapuram, Mappedu",
    bhk: ["3 BHK"],
    bhkFilter: ["3bhk"],
    units: 1,
    landArea: "1,300 sq.ft",
    builtUpArea: "1,300 sq.ft",
    year: "2023",
    image: "/image/residential_building_6.jpeg",
    aspectRatio: "3/4",
    description: "Contemporary 3 BHK G+1 individual villa in Kaspapuram, Mappedu built with high-grade steel and cement, custom architectural detailing, and landscaped yard."
  },
  {
    id: "p6",
    name: "2 BHK G+2 Apartment",
    location: "Kavangarai, Redhills",
    bhk: ["2 BHK"],
    bhkFilter: ["2bhk"],
    units: 6,
    landArea: "2,000 sq.ft",
    builtUpArea: "5,300 sq.ft",
    year: "2024",
    image: "/image/residential_building_4.jpeg",
    aspectRatio: "16/9",
    description: "Well-ventilated 2 BHK G+2 apartment complex in Kavangarai, Redhills built over 2,000 sq.ft plot with robust foundation engineering and turn-key handover."
  },
  {
    id: "p7",
    name: "3 BHK G+1 Duplex Villa",
    location: "Vengaivasel, Chennai",
    bhk: ["3 BHK"],
    bhkFilter: ["3bhk"],
    units: 1,
    landArea: "880 sq.ft",
    builtUpArea: "1,300 sq.ft",
    year: "2024",
    image: "/image/residential_building_8.jpeg",
    aspectRatio: "4/3",
    description: "Compact luxury 3 BHK G+1 duplex villa in Vengaivasel featuring smart spatial planning, modular interior provisions, and premium exterior elevation."
  },
  {
    id: "p8",
    name: "5 BHK G+2 Semi-Independent House",
    location: "Pallavaram, Chennai",
    bhk: ["5 BHK"],
    bhkFilter: ["5bhk"],
    units: 1,
    landArea: "1,400 sq.ft",
    builtUpArea: "2,600 sq.ft",
    year: "2024",
    image: "/image/residential_building_7.jpeg",
    aspectRatio: "3/4",
    description: "Grand 5 BHK G+2 semi-independent multi-family residence in Pallavaram crafted for multi-generational living with extensive balcony spaces and covered parking."
  },
  {
    id: "p9",
    name: "3 BHK G+2 Semi-Independent House / Apartment with 3 Units",
    location: "Thirumalisai, Chennai",
    bhk: ["3 BHK"],
    bhkFilter: ["3bhk"],
    units: 3,
    landArea: "1,800 sq.ft",
    builtUpArea: "3,200 sq.ft",
    year: "2023",
    image: "/image/residential_building_9.jpeg",
    aspectRatio: "16/10",
    description: "Versatile 3 BHK G+2 semi-independent residential apartment building in Thirumalisai featuring 3 distinct housing units with individual utility metering."
  },
  {
    id: "p10",
    name: "3 BHK G+2 Semi-Independent House / Apartment",
    location: "Thirumalisai, Chennai",
    bhk: ["3 BHK"],
    bhkFilter: ["3bhk"],
    units: 3,
    landArea: "1,800 sq.ft",
    builtUpArea: "3,200 sq.ft",
    year: "2023",
    image: "/image/residential_building_5.jpeg",
    aspectRatio: "16/10",
    description: "Versatile 3 BHK G+2 semi-independent residential apartment building in Thirumalisai featuring 3 distinct housing units with individual utility metering."
  }
];
